---

elasticsearch_exporter_private_tmp: false

elasticsearch_exporter_options:
  - es.uri=http://elasticsearch_exporter:9200

## Elasticsearch role
install_mode: deb
elasticsearch_api_port: 9200

elasticsearch_api_host: elasticsearch_exporter

elasticsearch_config:
  node.name: "{{ elasticsearch_api_host }}"
  cluster.name: idealista-cluster
  network.host: _site_
  discovery.type: "single-node"
  http.port: "{{ elasticsearch_api_port }}"
  bootstrap.memory_lock: true
  node.roles: [ master, data, ingest, transform ]
  xpack:
    security:
      enabled: false
      autoconfiguration:
        enabled: false
      http:
        ssl:
          enabled: false
      transport:
        ssl:
          enabled: false
elasticsearch_jvm_custom_parameters:
  - '-Xms256m'
  - '-Xmx256m'
  - '-Des.transport.cname_in_publish_address=true'

elasticsearch_os_tuning: false
