---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint -f colored .
  ansible-lint --force-color .
platforms:
  - name: elasticsearch_exporter
    groups:
      - elasticsearch_exporter_group
    image: ${MOLECULE_DISTRO:-idealista/jdk:11.0.20-bullseye-temurin-jdk}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    command: '/lib/systemd/systemd'
    cgroupns_mode: host
    stop_signal: 'RTMIN+3'
    networks:
      - name: prometheus-es-network
        aliases:
          - elasticsearch_exporter
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: 1
    PY_COLORS: 1
verifier:
  name: ansible
